### ISSUE TITLE
It breaks with blank lines in the csv

### ISSUE THREAD

**Issue by ophintor** [nhsd-a2si/logmunger#1]
When the doslog (csv) contains blank lines at the end of the file, the script fails with the error below:

```
Traceback (most recent call last):
  File "./logmunger.py", line 129, in <module>
    main(sys.stdout, *sys.argv)
  File "./logmunger.py", line 43, in main
    dos_data_dict = process_dos_file(parsed_args.doslog)
  File "./logmunger.py", line 102, in process_dos_file
    log_event = parse_dos_row_dict(dos_row_dict)
  File "./logmunger.py", line 111, in parse_dos_row_dict
    dos_row_dict['Date & Time'][:19], '%Y/%m/%d %H:%M:%S')
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/_strptime.py", line 359, in _strptime
    (data_string, format))
ValueError: time data '' does not match format '%Y/%m/%d %H:%M:%S'
```

It's probably worth checking for empty lines before doing the date validation and either delete them or ignore them.

**Comment by mcbhenwood** [comment]
OK I'll put together a fix for this, for the sake of posterity.

**Comment by ophintor** [comment]
Awesome thanks :-)

**Comment by mcbhenwood** [comment]
pls see https://github.com/nhsd-a2si/logmunger/pull/2

**Comment by mcbhenwood** [comment]
Merged.
